name: Hello Workflow
on: push
jobs:
  build:
    name: Run Action A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "Drapegnik"
